// <auto-generated />
using System;
using CarTracking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarTracking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarTracking.Domain.Entities.LocationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                    b.Property<double>("Latitude").IsRequired().HasColumnType("double precision");
                    b.Property<double>("Longitude").IsRequired().HasColumnType("double precision");
                    b.Property<DateTime>("RecordedAt").IsRequired().HasColumnType("timestamp with time zone");
                    b.Property<double>("Speed").IsRequired().HasColumnType("double precision");
                    b.Property<long>("VehicleId").IsRequired().HasColumnType("bigint");
                    b.HasKey("Id");
                    b.HasIndex("VehicleId", "RecordedAt").HasDatabaseName("IX_LocationHistory_VehicleId_RecordedAt");
                    b.ToTable("LocationHistory");
                });

            modelBuilder.Entity("CarTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);
                    b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("PlateNumber").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.HasKey("Id");
                    b.HasIndex("PlateNumber").IsUnique().HasDatabaseName("IX_Vehicles_PlateNumber");
                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarTracking.Domain.Entities.VehicleCurrentLocation", b =>
                {
                    b.Property<long>("VehicleId").HasColumnType("bigint").ValueGeneratedNever();
                    b.Property<double>("Latitude").IsRequired().HasColumnType("double precision");
                    b.Property<double>("Longitude").IsRequired().HasColumnType("double precision");
                    b.Property<DateTime>("RecordedAt").IsRequired().HasColumnType("timestamp with time zone");
                    b.Property<double>("Speed").IsRequired().HasColumnType("double precision");
                    b.HasKey("VehicleId");
                    b.ToTable("VehicleCurrentLocations");
                });

            modelBuilder.Entity("CarTracking.Domain.Entities.LocationHistory", b =>
                {
                    b.HasOne("CarTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("LocationHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTracking.Domain.Entities.VehicleCurrentLocation", b =>
                {
                    b.HasOne("CarTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("CurrentLocation")
                        .HasForeignKey("CarTracking.Domain.Entities.VehicleCurrentLocation", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("CurrentLocation");
                    b.Navigation("LocationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
